### ISSUE TITLE
(Feature request) Add precompiled ARM64 to releases for use with "charch"

### ISSUE THREAD

**Issue by nerd190** [tytydraco/microroot#1]
Hello mate! I see you have been busy! 😱 
This, charch and the community magisk repo.
AMAZING work bro! Thank you!
Anyhoo... Back on topic! As the title says, for charch purposes, a single arm64 release would cover 80% of charch's users, you could also add a link in charch's repo suggesting this as a great lightweight candidate, I feel that popularity will soon rise for this distro when thousands of Android users are clicking the star button for you because it is readily available to them, they may not have a PC, a decent PC, or just not geek enough for the terminal.
Thank you for kicking mucl, thank you for libc!!! It is BEAUTIFUL. Keep up the hard work your killin it!
P.S community repo app? How??? Me need modules!😁 👍

**Comment by tytydraco** [comment]
Thank you so much man, I love seeing people appreciate my work. That's a great idea, I'll build the latest version for both x86_64 and aarch64, maybe a few other architectures as well as an initial release. The only issue is that MicroRoot doesn't come with any kind of package manager [see here](https://buildroot.org/downloads/manual/manual.html#faq-no-binary-packages). Users can download their glibc packages and extract them to the rootfs manually, but it's definitely not as easy as something like Alpine. But still, good idea, I'll go ahead and build it!

**Comment by nerd190** [comment]
Thats awesome thanks again!!!
About the pkg management...
Nix is available to Alpine, could this theoretically be the pkg manager of choice? its goood! I was thinking of compiling go/rust/c binaries in Termux / Android, then placing them on my path within chroot to use them, I will test!

**Comment by tytydraco** [comment]
I've actually never heard of Nix, but that totally seems doable. Also for your usecase of compiling binaries, it should work fine :ok_hand:. I'm compiling forx86_64 and aarch64 right now, and likely armeabi7 afterwards. Thanks for supporting this project and helping keep it alive <3

**Comment by tytydraco** [comment]
https://github.com/tytydraco/microroot/releases/tag/microroot-v1.0

@5c0tt-b0t Enjoy!
